
import { ServiceOption, Language } from './types';

export const SERVICES: ServiceOption[] = [
  { id: 'branding', labelKey: 'service_branding_title', descriptionKey: 'service_branding_desc', icon: '🎨', basePrice: 800 },
  { id: 'web_design', labelKey: 'service_web_title', descriptionKey: 'service_web_desc', icon: '💻', basePrice: 1200 },
  { id: 'ecommerce', labelKey: 'service_eco_title', descriptionKey: 'service_eco_desc', icon: '🛒', basePrice: 2500 },
  { id: 'landing_page', labelKey: 'service_landing_title', descriptionKey: 'service_landing_desc', icon: '🚀', basePrice: 500 },
  { id: 'graphic_design', labelKey: 'service_graphic_title', descriptionKey: 'service_graphic_desc', icon: '📐', basePrice: 300 },
  { id: 'hosting_maintenance', labelKey: 'service_hosting_title', descriptionKey: 'service_hosting_desc', icon: '🛡️', basePrice: 50 }
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    brand_name: 'The Smart Corner',
    tagline: 'Tell me what you have in mind and let\'s design something amazing together.',
    step_1_title: 'Which services do you need?',
    step_2_title: 'Project Details',
    step_3_title: 'Timeline & Budget',
    step_4_title: 'Contact Information',
    step_5_title: 'Briefing Received!',
    step_5_desc: 'Thank you for your time. I have received your information and will contact you within 48 business hours.',
    btn_next: 'Continue',
    btn_back: 'Back',
    btn_finish: 'Finish & Send',
    btn_sending: 'Sending...',
    btn_close: 'Close',
    field_project_name: 'Project Name',
    field_project_desc: 'Short Description',
    field_target: 'Target Audience',
    field_deadline: 'When do you need it?',
    field_budget: 'Approximate Budget (Investment)',
    field_name: 'Full Name',
    field_email: 'Email',
    field_company: 'Company / Project',
    field_gdpr: 'I agree to have my data processed for commercial purposes.',
    ai_summary_title: 'YOUR REQUEST SUMMARY (AI)',
    internal_calc: 'Internal estimate',
    service_branding_title: 'Branding & Identity',
    service_branding_desc: 'Logos, brand manuals, color palettes, and typography.',
    service_web_title: 'Corporate Web Design',
    service_web_desc: 'Professional, responsive, and optimized websites.',
    service_eco_title: 'Online Store (E-commerce)',
    service_eco_desc: 'Sell your products with a robust and secure platform.',
    service_landing_title: 'Sales Landing Page',
    service_landing_desc: 'Pages focused on conversion for specific campaigns.',
    service_graphic_title: 'General Graphic Design',
    service_graphic_desc: 'Brochures, signage, social media, and print materials.',
    service_hosting_title: 'Hosting & Maintenance',
    service_hosting_desc: 'Own server, backups, and monthly updates.',
    budget_ranges: ['Under 1,000€', '1,000€ - 3,000€', '3,000€ - 5,000€', '5,000€ - 10,000€', 'Over 10,000€'],
    deadlines: ['Urgent (< 2 weeks)', 'Normal (1 month)', 'No rush (2-3 months)', 'Flexible']
  },
  es: {
    brand_name: 'The Smart Corner',
    tagline: 'Cuéntame qué tienes en mente y diseñemos algo increíble juntos.',
    step_1_title: '¿Qué servicios necesitas?',
    step_2_title: 'Detalles del Proyecto',
    step_3_title: 'Plazos y Presupuesto',
    step_4_title: 'Datos de contacto',
    step_5_title: '¡Briefing Recibido!',
    step_5_desc: 'Gracias por tu tiempo. He recibido la información y te contactaré en un máximo de 48h hábiles.',
    btn_next: 'Continuar',
    btn_back: 'Volver',
    btn_finish: 'Finalizar y Enviar',
    btn_sending: 'Enviando...',
    btn_close: 'Cerrar',
    field_project_name: 'Nombre del Proyecto',
    field_project_desc: 'Descripción breve',
    field_target: 'Público objetivo',
    field_deadline: '¿Para cuándo lo necesitas?',
    field_budget: 'Presupuesto aproximado (Inversión)',
    field_name: 'Nombre Completo',
    field_email: 'Email',
    field_company: 'Empresa / Proyecto',
    field_gdpr: 'Acepto que mis datos sean tratados para enviarme una propuesta comercial.',
    ai_summary_title: 'RESUMEN DE TU SOLICITUD (IA)',
    internal_calc: 'Cálculo estimado interno',
    service_branding_title: 'Branding e Identidad',
    service_branding_desc: 'Logotipos, manual de marca, paleta de colores y tipografía.',
    service_web_title: 'Diseño Web Corporativo',
    service_web_desc: 'Sitios web profesionales, adaptables y optimizados.',
    service_eco_title: 'Tienda Online (E-commerce)',
    service_eco_desc: 'Venta de productos con plataforma robusta y segura.',
    service_landing_title: 'Landing Page de Venta',
    service_landing_desc: 'Páginas enfocadas en conversión para campañas.',
    service_graphic_title: 'Diseño Gráfico General',
    service_graphic_desc: 'Folletos, cartelería, redes sociales y material impreso.',
    service_hosting_title: 'Hosting y Mantenimiento',
    service_hosting_desc: 'Servidor propio, backups y actualizaciones mensuales.',
    budget_ranges: ['Menos de 1.000€', '1.000€ - 3.000€', '3.000€ - 5.000€', '5.000€ - 10.000€', 'Más de 10.000€'],
    deadlines: ['Urgente (< 2 semanas)', 'Normal (1 mes)', 'Sin prisa (2-3 meses)', 'Flexible']
  },
  pl: {
    brand_name: 'The Smart Corner',
    tagline: 'Powiedz mi, co masz na myśli, i wspólnie zaprojektujmy coś niesamowitego.',
    step_1_title: 'Jakich usług potrzebujesz?',
    step_2_title: 'Szczegóły Projektu',
    step_3_title: 'Terminy i Budżet',
    step_4_title: 'Informacje Kontaktowe',
    step_5_title: 'Briefing Otrzymany!',
    step_5_desc: 'Dziękujemy za poświęcony czas. Otrzymaliśmy Twoje informacje i skontaktujemy się w ciągu 48 godzin roboczych.',
    btn_next: 'Kontynuuj',
    btn_back: 'Wstecz',
    btn_finish: 'Zakończ i Wyślij',
    btn_sending: 'Wysyłanie...',
    btn_close: 'Zamknij',
    field_project_name: 'Nazwa Projektu',
    field_project_desc: 'Krótki opis',
    field_target: 'Grupa docelowa',
    field_deadline: 'Na kiedy tego potrzebujesz?',
    field_budget: 'Przybliżony budżet (Inwestycja)',
    field_name: 'Imię i Nazwisko',
    field_email: 'Email',
    field_company: 'Firma / Projekt',
    field_gdpr: 'Wyrażam zgodę na przetwarzanie moich danych w celach handlowych.',
    ai_summary_title: 'PODSUMOWANIE TWOJEGO ZAPYTANIA (AI)',
    internal_calc: 'Wewnętrzna kalkulacja',
    service_branding_title: 'Branding i Tożsamość',
    service_branding_desc: 'Logotypy, księgi znaku, palety kolorów i typografia.',
    service_web_title: 'Projektowanie Stron WWW',
    service_web_desc: 'Profesjonalne, responsywne i zoptymalizowane strony.',
    service_eco_title: 'Sklep Internetowy (E-commerce)',
    service_eco_desc: 'Sprzedawaj swoje produkty na solidnej platformie.',
    service_landing_title: 'Landing Page Sprzedażowy',
    service_landing_desc: 'Strony skoncentrowane na konwersji dla kampanii.',
    service_graphic_title: 'Projektowanie Graficzne',
    service_graphic_desc: 'Broszury, szyldy, media społecznościowe i druk.',
    service_hosting_title: 'Hosting i Utrzymanie',
    service_hosting_desc: 'Własny serwer, kopie zapasowe i aktualizacje.',
    budget_ranges: ['Poniżej 1.000€', '1.000€ - 3.000€', '3.000€ - 5.000€', '5.000€ - 10.000€', 'Powyżej 10.000€'],
    deadlines: ['Pilne (< 2 tygodnie)', 'Normalne (1 miesiąc)', 'Bez pośpiechu (2-3 miesiące)', 'Elastyczne']
  }
};
